// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using khoaluantotnghiep.Data;

#nullable disable

namespace khoaluantotnghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013050615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("khoaluantotnghiep.Models.Admin", b =>
                {
                    b.Property<int>("MaAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaAdmin");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaAdmin"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.HasKey("MaAdmin");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Event", b =>
                {
                    b.Property<int>("MaSuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSuKien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<int>("MaToChuc")
                        .HasColumnType("int")
                        .HasColumnName("MaToChuc");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKetThuc");

                    b.Property<DateTime?>("NgayKetThucTuyen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKetThucTuyen");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime?>("NgayTuyen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTuyen");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenSuKien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaToChuc");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.LegalDocument", b =>
                {
                    b.Property<int>("MaGiayTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGiayTo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaGiayTo"));

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("File");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenGiayTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenGiayTo");

                    b.HasKey("MaGiayTo");

                    b.ToTable("LegalDocument");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Organization", b =>
                {
                    b.Property<int>("MaToChuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaToChuc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaToChuc"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<int?>("MaGiayTo")
                        .HasColumnType("int")
                        .HasColumnName("MaGiayTo");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("TenToChuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenToChuc");

                    b.HasKey("MaToChuc");

                    b.HasIndex("MaGiayTo");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.User", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LanDangNhapCuoi");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PasswordSalt");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VaiTro");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("User");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Volunteer", b =>
                {
                    b.Property<int>("MaTNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTNV"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.HasKey("MaTNV");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("Volunteer");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Admin", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Event", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("MaToChuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Organization", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.LegalDocument", "LegalDocument")
                        .WithMany()
                        .HasForeignKey("MaGiayTo");

                    b.HasOne("khoaluantotnghiep.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Volunteer", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
