// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using khoaluantotnghiep.Data;

#nullable disable

namespace khoaluantotnghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015154829_AddDiemTrungBinh")]
    partial class AddDiemTrungBinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("khoaluantotnghiep.Models.Admin", b =>
                {
                    b.Property<int>("MaAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaAdmin");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaAdmin"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("MaAdmin");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDanhGia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int")
                        .HasColumnName("DiemSo");

                    b.Property<int>("MaNguoiDanhGia")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDanhGia");

                    b.Property<int>("MaNguoiDuocDanhGia")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDuocDanhGia");

                    b.Property<int>("MaSuKien")
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NoiDung");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDanhGia");

                    b.HasIndex("MaNguoiDuocDanhGia");

                    b.HasIndex("MaSuKien");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.DonDangKy", b =>
                {
                    b.Property<int>("MaTNV")
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MaSuKien")
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaTNV");

                    b.HasIndex("MaSuKien");

                    b.ToTable("DonDangKy");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.GiayChungNhan", b =>
                {
                    b.Property<int>("MaGiayChungNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGiayChungNhan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaGiayChungNhan"));

                    b.Property<string>("File")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("File");

                    b.Property<int>("MaMau")
                        .HasColumnType("int")
                        .HasColumnName("MaMau");

                    b.Property<int>("MaTNV")
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayCap");

                    b.HasKey("MaGiayChungNhan");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaTNV");

                    b.ToTable("GiayChungNhan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.GiayToPhapLy", b =>
                {
                    b.Property<int>("MaGiayTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGiayTo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaGiayTo"));

                    b.Property<string>("File")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("File");

                    b.Property<int>("MaToChuc")
                        .HasColumnType("int")
                        .HasColumnName("MaToChuc");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenGiayTo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TenGiayTo");

                    b.HasKey("MaGiayTo");

                    b.HasIndex("MaToChuc");

                    b.ToTable("GiayToPhapLy");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.KyNang", b =>
                {
                    b.Property<int>("MaKyNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKyNang");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKyNang"));

                    b.Property<string>("TenKyNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenKyNang");

                    b.HasKey("MaKyNang");

                    b.ToTable("KyNang");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.LinhVuc", b =>
                {
                    b.Property<int>("MaLinhVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLinhVuc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLinhVuc"));

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenLinhVuc");

                    b.HasKey("MaLinhVuc");

                    b.ToTable("LinhVuc");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.MauGiayChungNhan", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaMau");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("File")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("File");

                    b.Property<int>("MaSuKien")
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayGui");

                    b.HasKey("MaMau");

                    b.HasIndex("MaSuKien");

                    b.ToTable("MauGiayChungNhan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.NguoiNhanThongBao", b =>
                {
                    b.Property<int>("MaNguoiNhanThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiNhanThongBao");

                    b.Property<int>("MaThongBao")
                        .HasColumnType("int")
                        .HasColumnName("MaThongBao");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaNguoiNhanThongBao");

                    b.HasIndex("MaThongBao");

                    b.ToTable("NguoiNhanThongBao");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien", b =>
                {
                    b.Property<int>("MaSuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSuKien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HinhAnh");

                    b.Property<int>("MaToChuc")
                        .HasColumnType("int")
                        .HasColumnName("MaToChuc");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKetThuc");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenSuKien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("TuyenBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTuyen");

                    b.Property<DateTime?>("TuyenKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKetThucTuyen");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaToChuc");

                    b.ToTable("SuKien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien_KyNang", b =>
                {
                    b.Property<int>("MaSuKien")
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int")
                        .HasColumnName("MaKyNang");

                    b.HasKey("MaSuKien", "MaKyNang");

                    b.HasIndex("MaKyNang");

                    b.ToTable("SuKien_KyNang");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien_LinhVuc", b =>
                {
                    b.Property<int>("MaSuKien")
                        .HasColumnType("int")
                        .HasColumnName("MaSuKien");

                    b.Property<int>("MaLinhVuc")
                        .HasColumnType("int")
                        .HasColumnName("MaLinhVuc");

                    b.HasKey("MaSuKien", "MaLinhVuc");

                    b.HasIndex("MaLinhVuc");

                    b.ToTable("SuKien_LinhVuc");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LanDangNhapCuoi");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PasswordSalt");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VaiTro");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaThongBao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayGui");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int")
                        .HasColumnName("PhanLoai");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien", b =>
                {
                    b.Property<int>("MaTNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTNV"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("DiemTrungBinh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.HasKey("MaTNV");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("TinhNguyenVien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien_KyNang", b =>
                {
                    b.Property<int>("MaTNV")
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int")
                        .HasColumnName("MaKyNang");

                    b.HasKey("MaTNV", "MaKyNang");

                    b.HasIndex("MaKyNang");

                    b.ToTable("TinhNguyenVien_KyNang");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien_LinhVuc", b =>
                {
                    b.Property<int>("MaTNV")
                        .HasColumnType("int")
                        .HasColumnName("MaTNV");

                    b.Property<int>("MaLinhVuc")
                        .HasColumnType("int")
                        .HasColumnName("MaLinhVuc");

                    b.HasKey("MaTNV", "MaLinhVuc");

                    b.HasIndex("MaLinhVuc");

                    b.ToTable("TinhNguyenVien_LinhVuc");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.ToChuc", b =>
                {
                    b.Property<int>("MaToChuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaToChuc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaToChuc"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DiaChi");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("DiemTrungBinh");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GioiThieu");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("longtext");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("MaTaiKhoan");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("TenToChuc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenToChuc");

                    b.Property<byte?>("TrangThaiXacMinh")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("MaToChuc");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("ToChuc");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.Admin", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.DanhGia", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "NguoiDanhGia")
                        .WithMany()
                        .HasForeignKey("MaNguoiDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "NguoiDuocDanhGia")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuocDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.SuKien", "Event")
                        .WithMany()
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("NguoiDanhGia");

                    b.Navigation("NguoiDuocDanhGia");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.DonDangKy", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.SuKien", "SuKien")
                        .WithMany()
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany()
                        .HasForeignKey("MaTNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKien");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.GiayChungNhan", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.MauGiayChungNhan", "MauGiayChungNhan")
                        .WithMany()
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany()
                        .HasForeignKey("MaTNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauGiayChungNhan");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.GiayToPhapLy", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.ToChuc", "ToChuc")
                        .WithMany("GiayToPhapLys")
                        .HasForeignKey("MaToChuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChuc");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.MauGiayChungNhan", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.SuKien", "SuKien")
                        .WithMany()
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.NguoiNhanThongBao", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaNguoiNhanThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.ThongBao", "ThongBao")
                        .WithMany()
                        .HasForeignKey("MaThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.ToChuc", "Organization")
                        .WithMany()
                        .HasForeignKey("MaToChuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien_KyNang", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.KyNang", "KyNang")
                        .WithMany()
                        .HasForeignKey("MaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.SuKien", "SuKien")
                        .WithMany("SuKien_KyNangs")
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien_LinhVuc", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.LinhVuc", "LinhVuc")
                        .WithMany()
                        .HasForeignKey("MaLinhVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.SuKien", "SuKien")
                        .WithMany("SuKien_LinhVucs")
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVuc");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.ThongBao", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien_KyNang", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.KyNang", "KyNang")
                        .WithMany()
                        .HasForeignKey("MaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany("TinhNguyenVien_KyNangs")
                        .HasForeignKey("MaTNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien_LinhVuc", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.LinhVuc", "LinhVuc")
                        .WithMany()
                        .HasForeignKey("MaLinhVuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("khoaluantotnghiep.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany("TinhNguyenVien_LinhVucs")
                        .HasForeignKey("MaTNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVuc");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.ToChuc", b =>
                {
                    b.HasOne("khoaluantotnghiep.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.SuKien", b =>
                {
                    b.Navigation("SuKien_KyNangs");

                    b.Navigation("SuKien_LinhVucs");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.TinhNguyenVien", b =>
                {
                    b.Navigation("TinhNguyenVien_KyNangs");

                    b.Navigation("TinhNguyenVien_LinhVucs");
                });

            modelBuilder.Entity("khoaluantotnghiep.Models.ToChuc", b =>
                {
                    b.Navigation("GiayToPhapLys");
                });
#pragma warning restore 612, 618
        }
    }
}
