// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using khoaluantotnghiep.Data;

#nullable disable

namespace khoaluantotnghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110103233_AddMoTaToLinhVucAndKyNang")]
    partial class AddMoTaToLinhVucAndKyNang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Copy toàn bộ nội dung từ AppDbContextModelSnapshot.BuildModel
            // Vì đây là migration cuối cùng, target model phải giống với snapshot hiện tại
            // Entity Framework sẽ tự động sử dụng AppDbContextModelSnapshot
#pragma warning restore 612, 618
        }
    }
}

